"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { formatCurrency } from "@/lib/format";

type ExportRow = {
  id: string;
  status: string;
  check_in_date: string | null;
  check_out_date: string | null;
  guest_name: string | null;
  unit_name: string | null;
  property_name: string | null;
  channel_name: string | null;
  source: string | null;
  total_amount: number | null;
  amount_paid: number | null;
  currency: string | null;
};

type ReservationsExportButtonProps = {
  rows: ExportRow[];
  isEn: boolean;
  locale: string;
  format: "csv" | "pdf";
};

function escapeCSV(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ReservationsExportButton({
  rows,
  isEn,
  locale,
  format,
}: ReservationsExportButtonProps) {
  const [generating, setGenerating] = useState(false);

  const headers = [
    isEn ? "Status" : "Estado",
    "Check-in",
    "Check-out",
    isEn ? "Guest" : "Huésped",
    isEn ? "Unit" : "Unidad",
    isEn ? "Property" : "Propiedad",
    isEn ? "Channel" : "Canal",
    isEn ? "Source" : "Origen",
    isEn ? "Amount" : "Monto",
    isEn ? "Paid" : "Pagado",
    isEn ? "Currency" : "Moneda",
  ];

  const toRow = (r: ExportRow): string[] => [
    r.status ?? "",
    r.check_in_date ?? "",
    r.check_out_date ?? "",
    r.guest_name ?? "",
    r.unit_name ?? "",
    r.property_name ?? "",
    r.channel_name ?? "",
    r.source ?? "manual",
    r.total_amount != null ? String(r.total_amount) : "",
    r.amount_paid != null ? String(r.amount_paid) : "",
    r.currency ?? "PYG",
  ];

  const handleCSV = () => {
    const lines = [
      headers.map(escapeCSV).join(","),
      ...rows.map((r) => toRow(r).map(escapeCSV).join(",")),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" });
    const date = new Date().toISOString().slice(0, 10);
    downloadBlob(blob, `reservations-${date}.csv`);
  };

  const handlePDF = async () => {
    setGenerating(true);
    try {
      const { default: jsPDF } = await import("jspdf");
      const autoTable = (await import("jspdf-autotable")).default;

      const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 10;
      let y = 15;

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(isEn ? "Reservations Report" : "Reporte de Reservas", margin, y);
      y += 6;

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      doc.text(
        `${isEn ? "Generated" : "Generado"}: ${new Date().toLocaleDateString(locale)} — ${rows.length} ${isEn ? "records" : "registros"}`,
        margin,
        y,
      );
      y += 6;

      const pdfHeaders = [
        isEn ? "Status" : "Estado",
        "Check-in",
        "Check-out",
        isEn ? "Guest" : "Huésped",
        isEn ? "Unit" : "Unidad",
        isEn ? "Source" : "Origen",
        isEn ? "Amount" : "Monto",
      ];

      const body = rows.map((r) => [
        r.status ?? "",
        r.check_in_date ?? "",
        r.check_out_date ?? "",
        r.guest_name ?? "",
        r.unit_name ?? "",
        r.source === "direct_booking" ? "Marketplace" : r.source ?? "Manual",
        r.total_amount != null
          ? formatCurrency(r.total_amount, r.currency ?? "PYG", locale)
          : "-",
      ]);

      autoTable(doc, {
        startY: y,
        head: [pdfHeaders],
        body,
        theme: "striped",
        headStyles: { fillColor: [41, 41, 41], fontSize: 8 },
        bodyStyles: { fontSize: 7 },
        columnStyles: { 6: { halign: "right" } },
        margin: { left: margin, right: margin },
      });

      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(150);
        const footerY = doc.internal.pageSize.getHeight() - 8;
        doc.text(
          `${isEn ? "Generated by" : "Generado por"} Casaora`,
          margin,
          footerY,
        );
        doc.text(
          `${isEn ? "Page" : "Página"} ${i}/${pageCount}`,
          pageWidth - margin,
          footerY,
          { align: "right" },
        );
      }

      const date = new Date().toISOString().slice(0, 10);
      doc.save(`reservations-${date}.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setGenerating(false);
    }
  };

  if (format === "csv") {
    return (
      <Button onClick={handleCSV} size="sm" variant="outline">
        CSV
      </Button>
    );
  }

  return (
    <Button disabled={generating} onClick={handlePDF} size="sm" variant="outline">
      {generating ? (
        <>
          <Spinner size="sm" />
          PDF...
        </>
      ) : (
        "PDF"
      )}
    </Button>
  );
}
